const COLORS=["#55dce4","#ed5c62","#62d68b","#a879e8","#f0ce58","#f17fc5"];
export function setupUI({game,network,voice}){const menu=document.getElementById("menu"),hud=document.getElementById("hud"),chars=document.getElementById("characters"),status=document.getElementById("menuStatus");let selected=Number(localStorage.selectedCharacter||0);
COLORS.forEach((c,i)=>{const d=document.createElement("button");d.className="char"+(i===selected?" selected":"");d.innerHTML=`<i style="background:${c}"></i>`;d.onclick=()=>{selected=i;document.querySelectorAll(".char").forEach(x=>x.classList.remove("selected"));d.classList.add("selected")};chars.append(d)});
const name=document.getElementById("username");name.value=localStorage.lastUsername||"";
function connect(room){const n=(name.value.trim()||"LumiPlayer").slice(0,16);localStorage.lastUsername=n;localStorage.selectedCharacter=selected;status.textContent="Finding Players...";network.connect({username:n,character:selected,room})}
document.getElementById("play").onclick=()=>connect(null);document.getElementById("create").onclick=()=>connect("CREATE");document.getElementById("join").onclick=()=>document.getElementById("roomInput").classList.toggle("hidden");document.getElementById("joinCode").onclick=()=>{const c=document.getElementById("roomCode").value.trim().toUpperCase();if(c)connect(c)};
network.on("welcome",()=>{menu.classList.add("hidden");hud.classList.remove("hidden");const u=new URL(location.href);u.searchParams.set("room",network.room);history.replaceState({},'',u)});
network.on("room-full",()=>status.textContent="Room is full");network.on("error",m=>status.textContent=m.message||"Server error");
const send=()=>{const i=document.getElementById("chatInput"),t=i.value.trim();if(t){network.chat(t);i.value=""}};document.getElementById("sendChat").onclick=send;document.getElementById("chatInput").onkeydown=e=>e.key==="Enter"&&send();
async function mic(){const on=await voice.toggle();document.getElementById("micBtn").textContent=on?"🔊":"🎙";document.getElementById("mobileMic").textContent=on?"🔊":"🎙"}document.getElementById("micBtn").onclick=mic;document.getElementById("mobileMic").onclick=mic;
function toggle(el){el.classList.toggle("hidden")}document.getElementById("mapBtn").onclick=()=>toggle(document.getElementById("mapOverlay"));document.getElementById("closeMap").onclick=()=>toggle(document.getElementById("mapOverlay"));document.getElementById("invBtn").onclick=()=>toggle(document.getElementById("inventoryOverlay"));document.getElementById("closeInv").onclick=()=>toggle(document.getElementById("inventoryOverlay"));document.getElementById("menuBtn").onclick=()=>toggle(menu);
document.getElementById("jumpBtn").onpointerdown=()=>game.input.jump=true;document.getElementById("jumpBtn").onpointerup=()=>game.input.jump=false;document.getElementById("interactBtn").onclick=()=>network.interact("pulse");document.getElementById("buildBtn").onclick=()=>network.build(0);
const joy=document.getElementById("joystick"),knob=joy.querySelector("span");function joyMove(e){const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,l=Math.min(Math.hypot(dx,dy),34),a=Math.atan2(dy,dx);const x=Math.cos(a)*l/34,y=Math.sin(a)*l/34;knob.style.transform=`translate(${x*25}px,${y*25}px)`;game.mobileVec={x,y}}function joyEnd(){knob.style.transform="";game.mobileVec=null}joy.onpointermove=joyMove;joy.onpointerdown=e=>{joy.setPointerCapture(e.pointerId);joyMove(e)};joy.onpointerup=joyEnd;joy.onpointercancel=joyEnd;
const roomQ=new URLSearchParams(location.search).get("room");if(roomQ){document.getElementById("roomCode").value=roomQ;document.getElementById("roomInput").classList.remove("hidden")}setTimeout(()=>menu.classList.remove("hidden"),1200);
}