import {World} from "./world.js";import {Player} from "./player.js";import {Camera} from "./camera.js";import {blocked} from "./collision.js";import {EVENT_META} from "./events.js";
export class Game{
 constructor(canvas,cfg){this.canvas=canvas;this.ctx=canvas.getContext("2d");this.cfg=cfg;this.world=new World(cfg);this.camera=new Camera(canvas,cfg.WORLD.w,cfg.WORLD.h);this.players=new Map();this.input={x:0,y:0,run:false,jump:false};this.last=performance.now();this.running=false;this.event=null;this.objective=null;this.bind();this.resize();addEventListener("resize",()=>this.resize())}
 attachNetwork(net,voice){this.net=net;this.voice=voice;net.on("welcome",m=>{this.players.set(m.id,new Player({...m.player,id:m.id},true));this.objective=m.objective;this.event=m.event;this.start()});net.on("state",m=>{for(const p of m.players){if(p.id===net.clientId)continue;let pl=this.players.get(p.id);if(!pl){pl=new Player(p);this.players.set(p.id,pl)}Object.assign(pl,{name:p.name,color:p.color,targetX:p.x,targetY:p.y,state:p.state,mic:p.mic})}});net.on("player-left",m=>this.players.delete(m.id));net.on("objective",m=>{this.objective=m.objective;this.toast(`Objective: ${m.objective.name}`)});net.on("event",m=>{this.event=m.event;this.showEvent(m.event)});net.on("build-state",m=>this.world.buildings=m.buildings||[]);net.on("chat",m=>this.chat(m));net.on("status",s=>this.status(s))}
 bind(){this.keys=new Set();addEventListener("keydown",e=>{this.keys.add(e.code);if(["Space","ArrowUp","ArrowDown","ArrowLeft","ArrowRight"].includes(e.code))e.preventDefault();if(e.code==="KeyE"&&!e.repeat)this.net?.interact("pulse");if(e.code==="KeyB"&&!e.repeat)this.net?.build(0)});addEventListener("keyup",e=>this.keys.delete(e.code))}
 setMobile(x,y){this.input.x=x;this.input.y=y}
 updateInput(){if(this.mobileVec){this.input.x=this.mobileVec.x;this.input.y=this.mobileVec.y}else{this.input.x=(this.keys.has("KeyD")||this.keys.has("ArrowRight")?1:0)-(this.keys.has("KeyA")||this.keys.has("ArrowLeft")?1:0);this.input.y=(this.keys.has("KeyS")||this.keys.has("ArrowDown")?1:0)-(this.keys.has("KeyW")||this.keys.has("ArrowUp")?1:0)}this.input.run=this.keys.has("ShiftLeft")||this.keys.has("ShiftRight");this.input.jump=this.keys.has("Space")}
 start(){if(this.running)return;this.running=true;requestAnimationFrame(t=>this.loop(t))}
 loop(t){const dt=Math.min(.05,(t-this.last)/1000);this.last=t;this.updateInput();const me=this.players.get(this.net?.clientId);if(me){const ox=me.x,oy=me.y;me.update(dt,this.input);if(blocked(this.world,me.x,me.y)){me.x=ox;me.y=oy}if(Math.hypot(me.x-ox,me.y-oy)>2)this.net?.move(me.x,me.y,me.state,this.input.jump)}this.world.update(dt,this.event==="HEAVY_WIND"||this.event==="PIXEL_STORM"?.9:.4);this.camera.zoom=Math.max(.78,Math.min(1.25,Math.min(innerWidth/900,innerHeight/620)));this.camera.update(me||{x:1800,y:1200},dt);this.draw();requestAnimationFrame(q=>this.loop(q))}
 draw(){const c=this.ctx,w=innerWidth,h=innerHeight;c.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);c.clearRect(0,0,w,h);const z=this.camera.zoom;this.world.draw(c,this.camera,z,this.event);const ps=[...this.players.values()].sort((a,b)=>a.y-b.y);for(const p of ps){p.draw(c,z,this.camera);this.label(c,p,z)}this.vignette(c,w,h);this.hud()}
 label(c,p,z){c.save();c.font=`bold ${Math.max(9,10*z)}px monospace`;c.textAlign="center";c.fillStyle="#eaffff";c.shadowColor="#001014";c.shadowBlur=4;c.fillText((p.mic?"🎙 ":"")+p.name,(p.x-this.camera.x)*z,(p.y-this.camera.y-30)*z);c.restore()}
 vignette(c,w,h){const g=c.createRadialGradient(w/2,h/2,Math.min(w,h)*.15,w/2,h/2,Math.max(w,h)*.75);g.addColorStop(0,"transparent");g.addColorStop(1,"rgba(0,0,0,.3)");c.fillStyle=g;c.fillRect(0,0,w,h)}
 hud(){document.getElementById("roomLabel").textContent=`ROOM ${this.net?.room||"—"}`;document.getElementById("playersLabel").textContent=`${this.players.size} / 20`;if(this.objective){document.getElementById("objectiveText").textContent=this.objective.name;document.getElementById("objectiveStage").textContent=`STAGE ${Math.min((this.objective.progress||0)+1,this.objective.stages)}/${this.objective.stages}`;document.getElementById("objectiveProgress").style.width=`${Math.min(100,(this.objective.progress||0)/this.objective.stages*100)}%`}}
 status(s){const e=document.getElementById("connection");e.className="connection";e.querySelector("b").textContent=s;if(s==="Connected"){e.classList.add("connected");setTimeout(()=>e.classList.add("hidden"),900)}else if(s==="Connection Failed")e.classList.add("failed")}
 showEvent(ev){const b=document.getElementById("eventBanner");document.getElementById("eventText").textContent=EVENT_META[ev]||ev.replaceAll("_"," ");b.classList.remove("hidden");if(ev==="GLITCH_EVENT")b.classList.add("glitch");setTimeout(()=>{b.classList.add("hidden");b.classList.remove("glitch")},6500);this.toast(`WORLD EVENT: ${EVENT_META[ev]||ev}`)}
 toast(s){const e=document.getElementById("toast");e.textContent=s;e.classList.add("show");clearTimeout(this._toast);this._toast=setTimeout(()=>e.classList.remove("show"),2200)}
 chat(m){const box=document.getElementById("chat"),e=document.createElement("div");e.className="msg";const b=document.createElement("b"),t=document.createTextNode(m.text);b.textContent=m.name;e.append(b,t);box.append(e);while(box.children.length>8)box.firstChild.remove();setTimeout(()=>e.remove(),11000)}
 resize(){this.canvas.width=innerWidth*devicePixelRatio;this.canvas.height=innerHeight*devicePixelRatio;this.canvas.style.width=innerWidth+"px";this.canvas.style.height=innerHeight+"px"}
}